"use client";
import { useEffect, useMemo, useState } from "react";
import { Badge, Button, ConfidenceBadge, Dialog, Drawer, MiniBar, NumberInput, Panel, Stat, StatRow, TextInput, Tooltip } from "@/ui";
import type { BuildWeaponResponse, CompatibleMod, Scenario, WeaponDetail, WeaponListItem } from "@/server/contracts";
import "./weapon-builder.css";

const blankScenario: Scenario = { headshots: false, statusTypesOnTarget: 0, killStacks: 0, arcaneStacks: 0, level: 100, enemyArchetypeId: "heavy_gunner", faction: "Grineer", steelPath: false };
const enemies = ["lancer", "elite_lancer", "heavy_gunner", "bombard", "nox", "demolisher", "crewman", "tech", "moa", "nullifier", "charger", "ancient_healer", "toxic_ancient", "corrupted_heavy", "corrupted_bombard", "eximus_gunner", "acolyte"];
const metric = (result: BuildWeaponResponse | null, key: string) => result?.stats.find((stat) => stat.key === key);
const format = (value?: number) => value === undefined || !Number.isFinite(value) ? "—" : Intl.NumberFormat("en-US", { maximumFractionDigits: value >= 1000 ? 0 : 2 }).format(value);
function Delta({ before, after }: { before?: number; after?: number }) { if (before === undefined || after === undefined || before === after) return null; const pct = before ? ((after - before) / before) * 100 : 0; return <span className={pct >= 0 ? "delta--positive builder-delta" : "delta--negative builder-delta"} data-delta>{format(before)} → {format(after)} {pct >= 0 ? "+" : ""}{pct.toFixed(1)}%</span>; }

export function WeaponBuilder() {
  const [weapons, setWeapons] = useState<WeaponListItem[]>([]), [weaponId, setWeaponId] = useState<string | null>(null), [detail, setDetail] = useState<WeaponDetail | null>(null);
  const [slots, setSlots] = useState<{ modId: string; rank: number; slotIndex: number }[]>([]), [arcaneIds, setArcaneIds] = useState<string[]>([]), [riven, setRiven] = useState([{ stat: "damage", value: 0 }, { stat: "criticalChance", value: 0 }, { stat: "statusChance", value: 0 }]);
  const [scenario, setScenario] = useState<Scenario>(blankScenario), [result, setResult] = useState<BuildWeaponResponse | null>(null), [previous, setPrevious] = useState<BuildWeaponResponse | null>(null), [calculating, setCalculating] = useState(false), [picker, setPicker] = useState<"weapon" | "arcane" | number | null>(null), [query, setQuery] = useState("");
  const weapon = weapons.find((item) => item.id === weaponId);
  useEffect(() => { fetch("/api/weapons").then((r) => r.json()).then(setWeapons).catch(() => setWeapons([])); }, []);
  useEffect(() => { if (!weaponId) return; fetch(`/api/weapons/${weaponId}`).then((r) => r.json()).then((next) => { setDetail(next); setSlots([]); setArcaneIds([]); setResult(null); setPrevious(null); }).catch(() => setDetail(null)); }, [weaponId]);
  useEffect(() => { if (!weaponId || !detail) return; const controller = new AbortController(); const timer = setTimeout(async () => { setCalculating(true); try { const rivenStatChanges = Object.fromEntries(riven.filter((item) => item.stat && item.value).map((item) => [item.stat, item.value / 100])); const response = await fetch("/api/build/weapon", { method: "POST", headers: { "Content-Type": "application/json" }, signal: controller.signal, body: JSON.stringify({ weaponId, modSlots: slots, arcaneIds, rivenStatChanges, scenario }) }); if (!response.ok) throw new Error("Calculation failed"); const next = await response.json() as BuildWeaponResponse; setPrevious(result); setResult(next); } catch (error) { if ((error as Error).name !== "AbortError") console.error(error); } finally { setCalculating(false); } }, 150); return () => { clearTimeout(timer); controller.abort(); }; }, [weaponId, detail, slots, arcaneIds, riven, scenario]);
  const visibleWeapons = useMemo(() => weapons.filter((item) => item.name.toLowerCase().includes(query.toLowerCase())), [weapons, query]);
  const chooseMod = (mod: CompatibleMod, index: number) => { setSlots((old) => [...old.filter((slot) => slot.slotIndex !== index), { modId: mod.id, rank: mod.maxRank, slotIndex: index }].sort((a, b) => a.slotIndex - b.slotIndex)); setPicker(null); };
  if (!weaponId || !detail || !weapon) return <div className="builder-empty"><Panel chamfer title="Weapon Builder"><p>Choose a weapon to begin.</p><Button size="md" onClick={() => setPicker("weapon")}>Choose weapon</Button></Panel><WeaponPicker open={picker === "weapon"} onOpenChange={(open) => setPicker(open ? "weapon" : null)} weapons={visibleWeapons} query={query} setQuery={setQuery} select={(id) => { setWeaponId(id); setQuery(""); setPicker(null); }} /></div>;
  const dps = metric(result, "sustainedDps"), burst = metric(result, "burstDps"), hit = metric(result, "totalDamage"), ttk = result?.ttk;
  return <div className="weapon-builder"><header className="weapon-focus"><div><p className="eyebrow">Weapon configuration</p><h1>{weapon.name}</h1><div className="weapon-chips"><Badge>MR {weapon.masteryReq}</Badge><Badge>Disposition {weapon.disposition.toFixed(2)}</Badge>{weapon.isIncarnon && <Badge variant="rare">Incarnon</Badge>}</div></div><Button variant="secondary" onClick={() => setPicker("weapon")}>Switch weapon</Button></header>
    <section className={calculating ? "metrics metrics--calculating" : "metrics"} aria-live="polite"><StatRow>{[["Sustained DPS", dps, "sustainedDps"], ["Burst DPS", burst, "burstDps"], ["Average Hit", hit, "totalDamage"]].map(([label, stat, key]) => <Stat key={key as string} label={label as string} value={<><span data-metric={key as string}>{format((stat as typeof dps)?.value)}</span><Delta before={metric(previous, key as string)?.value} after={(stat as typeof dps)?.value} /></>} confidence={(stat as typeof dps)?.confidence} />)}<Stat label="Expected TTK" value={<><span>{format(ttk?.value)}</span><Delta before={previous?.ttk?.value} after={ttk?.value} /></>} confidence={ttk?.confidence} /></StatRow></section>
    <div className="builder-profiles"><Panel title="Damage profile" chamfer><div className="damage-stack">{[detail.base.impact, detail.base.puncture, detail.base.slash, detail.base.heat, detail.base.cold, detail.base.toxin, detail.base.electricity].filter(Boolean).map((value, index) => <span key={index} style={{ width: `${(value / Math.max(detail.base.damage, 1)) * 100}%` }} />)}</div><div className="profile-legend">Impact {detail.base.impact} · Puncture {detail.base.puncture} · Slash {detail.base.slash}</div><ConfidenceBadge tag="verified" /></Panel><Panel title="Critical profile" chamfer><strong>{(detail.base.criticalChance * 100).toFixed(0)}% CC · {detail.base.criticalMultiplier.toFixed(1)}× CM</strong><p className="muted">Tier {(detail.base.criticalChance * detail.base.criticalMultiplier >= 1 ? "reliable" : "base")}</p><ConfidenceBadge tag="verified" /></Panel><Panel title="Status output" chamfer><strong>{((detail.base.statusChance ?? 0) * detail.base.fireRate).toFixed(2)} / sec</strong><p className="muted">Status probability follows the current damage profile.</p><ConfidenceBadge tag="approximation" /></Panel></div>
    <Panel title="Mod configuration" chamfer><div className="mod-slots">{Array.from({ length: detail.modSlotCount + (detail.exilus ? 1 : 0) }, (_, index) => { const slot = slots.find((item) => item.slotIndex === index), mod = detail.mods.find((item) => item.id === slot?.modId), contribution = result?.perModContribution.find((item) => item.modId === mod?.id); return <Tooltip key={index} label={mod ? `${mod.primaryEffect}${contribution ? ` · ${format(contribution.dpsDelta)} DPS (${contribution.pct.toFixed(1)}%)` : ""}` : "Empty tactical slot"}><button className="mod-slot" onClick={() => setPicker(index)}>{mod ? <><span className="mod-slot__rarity">◆</span><b>{mod.name}</b><small>{mod.primaryEffect}</small><span className="mod-slot__rank"><button aria-label={`Decrease ${mod.name} rank`} onClick={(event) => { event.stopPropagation(); setSlots((old) => old.map((item) => item.slotIndex === index ? { ...item, rank: Math.max(0, item.rank - 1) } : item)); }}>−</button>{slot?.rank}/{mod.maxRank}<button aria-label={`Increase ${mod.name} rank`} onClick={(event) => { event.stopPropagation(); setSlots((old) => old.map((item) => item.slotIndex === index ? { ...item, rank: Math.min(mod.maxRank, item.rank + 1) } : item)); }}>+</button></span></> : <><span className="mod-slot__polarity">{detail.polarities[index] ?? "◇"}</span><b>Empty slot</b><small>+</small></>}</button></Tooltip>; })}</div></Panel>
    <div className="builder-lower"><Panel title="Arcane" chamfer><div className="arcane-slots">{Array.from({ length: Math.max(1, detail.arcaneSlots) }, (_, index) => <button key={index} className="mod-slot" onClick={() => setPicker("arcane")}>{arcaneIds[index] ? arcaneIds[index].replaceAll("_", " ") : "+ Add arcane"}</button>)}</div><p className="muted">Stack count is controlled in Scenario.</p></Panel><Panel title="Riven stat input" chamfer><div className="riven-rows">{riven.map((item, index) => <div key={index}><select value={item.stat} onChange={(event) => setRiven((old) => old.map((row, i) => i === index ? { ...row, stat: event.target.value } : row))}><option value="damage">Damage</option><option value="criticalChance">Critical chance</option><option value="criticalMultiplier">Critical damage</option><option value="statusChance">Status chance</option><option value="multishot">Multishot</option></select><NumberInput aria-label={`Riven ${item.stat}`} value={item.value} onChange={(event) => setRiven((old) => old.map((row, i) => i === index ? { ...row, value: Number(event.target.value) } : row))} /></div>)}</div></Panel><ScenarioPanel scenario={scenario} setScenario={setScenario} enemies={enemies} /></div>
    <Panel title="Detailed calculations" chamfer><details><summary>Show calculation evidence</summary><div className="details-list">{result?.stats.map((stat) => <div key={stat.key}><span>{stat.label}</span><strong>{format(stat.value)}</strong><ConfidenceBadge tag={stat.confidence} /></div>)}{result?.caveats.map((caveat) => <p key={caveat}>{caveat}</p>)}{result?.ttk?.caveats.map((caveat) => <p key={caveat.key}><ConfidenceBadge tag={caveat.tag} /> {caveat.text}</p>)}</div></details></Panel>
    <WeaponPicker open={picker === "weapon"} onOpenChange={(open) => setPicker(open ? "weapon" : null)} weapons={visibleWeapons} query={query} setQuery={setQuery} select={(id) => { setWeaponId(id); setQuery(""); setPicker(null); }} />
    <Drawer open={typeof picker === "number"} onOpenChange={(open) => setPicker(open ? picker : null)} title="Compatible mods"><TextInput autoFocus placeholder="Search mods" value={query} onChange={(event) => setQuery(event.target.value)} /><div className="picker-list">{detail.mods.filter((mod) => mod.name.toLowerCase().includes(query.toLowerCase())).map((mod) => <button key={mod.id} onClick={() => chooseMod(mod, picker as number)}><b>{mod.name}</b><span>{mod.primaryEffect} · {mod.polarity}</span></button>)}</div></Drawer>
    <Drawer open={picker === "arcane"} onOpenChange={(open) => setPicker(open ? "arcane" : null)} title="Weapon arcanes"><div className="picker-list">{["arcane_primary_merciless", "arcane_primary_deadhead", "arcane_primary_dexterity"].map((id) => <button key={id} onClick={() => { setArcaneIds([id]); setPicker(null); }}><b>{id.replaceAll("arcane_", "").replaceAll("_", " ")}</b><span>Weapon arcane</span></button>)}</div></Drawer>
  </div>;
}
function WeaponPicker({ open, onOpenChange, weapons, query, setQuery, select }: { open: boolean; onOpenChange: (open: boolean) => void; weapons: WeaponListItem[]; query: string; setQuery: (value: string) => void; select: (id: string) => void }) { return <Dialog open={open} onOpenChange={onOpenChange} title="Select weapon"><TextInput autoFocus placeholder="Search weapons" value={query} onChange={(event) => setQuery(event.target.value)} /><div className="picker-list">{weapons.map((item) => <button key={item.id} onClick={() => select(item.id)}><b>{item.name}</b><span>{item.category} · MR {item.masteryReq}</span></button>)}</div></Dialog>; }
function ScenarioPanel({ scenario, setScenario, enemies }: { scenario: Scenario; setScenario: (scenario: Scenario) => void; enemies: string[] }) { const set = <K extends keyof Scenario>(key: K, value: Scenario[K]) => setScenario({ ...scenario, [key]: value }); return <Panel title="Scenario" chamfer><div className="scenario-fields"><label>Faction<select value={scenario.faction} onChange={(event) => set("faction", event.target.value)}><option>Grineer</option><option>Corpus</option><option>Infested</option></select></label><label>Enemy<select value={scenario.enemyArchetypeId} onChange={(event) => set("enemyArchetypeId", event.target.value)}>{enemies.map((id) => <option key={id}>{id}</option>)}</select></label><label>Level<NumberInput value={scenario.level} onChange={(event) => set("level", Number(event.target.value))} /></label>{(["steelPath", "headshots"] as const).map((key) => <label key={key}><input type="checkbox" checked={Boolean(scenario[key])} onChange={(event) => set(key, event.target.checked)} />{key === "headshots" ? "Headshots (on/off)" : "Steel Path"}</label>)}{([ ["statusTypesOnTarget", "Status types on target (count)", 5], ["killStacks", "Kill stacks", 5], ["arcaneStacks", "Arcane stacks", 99] ] as const).map(([key, label, max]) => <label key={key}>{label}<NumberInput min={0} max={max} value={scenario[key]} onChange={(event) => set(key, Math.max(0, Math.min(max, Number(event.target.value))))} /></label>)}</div><p className="muted">Armor strip and status uptime are derived by the simulation, not set here.</p></Panel>; }
