"use client";
import { useState } from "react";
import { Badge, Button, Card, ConfidenceBadge, Dialog, IconButton, Kbd, Label, MiniBar, NumberInput, Panel, RadialMeter, SegmentedControl, Sparkline, Stat, StatGrid, StatRow, Table, Tabs, TextInput, Tooltip } from "@/ui";
const colors = [["bg", "#0a0b0d", "text-primary", "#e9eaec"], ["surface-1", "#101216", "text-primary", "#e9eaec"], ["surface-2", "#171a1f", "text-primary", "#e9eaec"], ["surface-3", "#1f232a", "text-primary", "#e9eaec"], ["accent", "#46a9b7", "accent-contrast", "#04191c"], ["positive", "#5bb47b", "bg", "#0a0b0d"], ["negative", "#d75c52", "bg", "#0a0b0d"], ["warning", "#d9a441", "bg", "#0a0b0d"], ["info", "#5b93c4", "bg", "#0a0b0d"]] as const;
function contrast(a: string, b: string) { const lum = (hex: string) => { const n = hex.slice(1).match(/../g)!.map((x) => parseInt(x, 16) / 255).map((x) => x <= .03928 ? x / 12.92 : ((x + .055) / 1.055) ** 2.4); return .2126 * n[0] + .7152 * n[1] + .0722 * n[2]; }; const [l1, l2] = [lum(a), lum(b)].sort((x, y) => y - x); return ((l1 + .05) / (l2 + .05)).toFixed(2); }
export default function ComponentsPage() { const [segment, setSegment] = useState("Standard"); const [open, setOpen] = useState(false); const [moving, setMoving] = useState(false); return <main className="page"><h1 className="page-title">Components / Foundation</h1><p className="muted">Token review surface. Body text uses primary or secondary text only; tertiary remains metadata.</p>
<h2 className="section-label">Color and contrast</h2><div className="grid gallery-grid">{colors.map(([name, hex, against, againstHex]) => <Panel key={name} title={name}><div style={{ height: "var(--space-10)", background: `var(--${name})` }} /><p className="mono">{hex}</p><p className="muted">{against} · {contrast(hex, againstHex)}:1</p></Panel>)}</div>
<h2 className="section-label">Scale</h2><Panel title="Spacing · type · corners" chamfer><div className="grid gallery-grid">{["0", "1", "2", "3", "4", "5", "6", "8", "10", "12", "16"].map((n) => <div key={n}><span className="label">space {n}</span><div style={{ width: `var(--space-${n})`, height: "var(--space-3)", background: "var(--accent)" }} /></div>)}<div><p style={{ font: "var(--text-display-lg)" }}>Display 28</p><p style={{ font: "var(--text-display-md)" }}>Display 20</p><p style={{ font: "var(--text-title)" }}>Title 15</p><p className="label">Label 11</p><p className="mono">4,481,102.34 mono</p></div><div><div className="card">radius md</div><div className="panel chamfer" style={{ marginTop: "var(--space-3)", padding: "var(--space-3)" }}>chamfered panel</div></div></div></Panel>
<h2 className="section-label">Motion</h2><Panel title="Precise / reduced-motion aware"><Button onClick={() => setMoving(!moving)}>Play fast / base / slow</Button><span className="mono" style={{ display: "inline-block", marginLeft: "var(--space-4)", transform: moving ? "translateX(var(--space-8))" : "translateX(0)", transition: "transform var(--dur-slow) var(--ease-standard)" }}>◈ transition sample</span></Panel>
<h2 className="section-label">Actions and fields</h2><Panel title="Buttons"><div className="grid gallery-grid"><Button>Primary</Button><Button variant="secondary">Secondary</Button><Button variant="ghost">Ghost</Button><Button variant="danger">Danger</Button><Button disabled>Disabled</Button><IconButton label="Sample action">◈</IconButton><Kbd>Ctrl K</Kbd></div><div className="grid gallery-grid" style={{ marginTop: "var(--space-4)" }}><div className="field"><Label htmlFor="sample-text">Label</Label><TextInput id="sample-text" placeholder="Text input" /></div><div className="field"><Label htmlFor="sample-number">Value</Label><NumberInput id="sample-number" defaultValue="1250" /></div></div></Panel>
<h2 className="section-label">Information primitives</h2><Panel title="Stats" inset><StatGrid><Stat label="Sustained DPS" value="3.81m" delta={18.4} confidence="verified" /><Stat label="Status output" value="104.8" delta={-4.2} confidence="approximation" /><Stat label="Unmodeled" value="—" confidence="not-modeled" /></StatGrid><StatRow><Stat label="Critical chance" value="128%" /><Stat label="Reload" value="1.7s" /></StatRow></Panel><div className="grid gallery-grid" style={{ marginTop: "var(--space-4)" }}><Card>Card: reserve for a genuinely self-contained item.</Card><Panel title="Badges"><div className="grid"><Badge variant="positive">Positive</Badge><Badge variant="rare">Rare</Badge><Badge variant="legendary">Legendary</Badge>{(["verified", "approximation", "not-modeled", "pending-verification"] as const).map((tag) => <ConfidenceBadge key={tag} tag={tag} />)}</div></Panel></div>
<h2 className="section-label">Controls and disclosure</h2><Panel title="Keyboard control"><SegmentedControl options={["Standard", "Steel Path", "Circuit"]} value={segment} onChange={setSegment} /><Tabs tabs={[{ label: "Summary", content: <p className="muted">Underline tabs keep navigation compact.</p> }, { label: "Details", content: <p className="muted">Arrow keys cycle the selected tab.</p> }]} /><Tooltip label="Progressive disclosure via tooltip"><Button variant="ghost">Hover or focus</Button></Tooltip><Button variant="secondary" onClick={() => setOpen(true)}>Open dialog</Button><Dialog open={open} onOpenChange={setOpen} title="Foundation dialog">Escape and backdrop close this overlay.</Dialog></Panel>
<h2 className="section-label">Dense table and data atoms</h2><Table stickyHeader headers={["Metric", "Value", "Delta"]} rows={[["Burst DPS", "4,812,441", "+12.4%"], ["TTK", "0.84s", "−5.2%"]]} /><div className="grid gallery-grid" style={{ marginTop: "var(--space-4)" }}><Panel title="Sparkline"><Sparkline values={[12, 18, 16, 31, 27, 45, 52]} /></Panel><Panel title="Mini bar"><MiniBar value={68} /></Panel><Panel title="Radial meter"><RadialMeter value={72} /></Panel></div></main>; }
