"use client";

import * as DialogPrimitive from "@radix-ui/react-dialog";
import { Command } from "cmdk";
import { Bell, CircleUser, Globe, PanelLeftClose, PanelLeftOpen, Sparkles } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { type ReactNode, useEffect, useState } from "react";
import { IconButton, Kbd } from "@/ui";
import { flattenedNavigation, navigation } from "./navigation";
import "./shell.css";

function titleFor(path: string) { return flattenedNavigation.find((item) => item.href === path)?.label ?? "Workspace"; }
function Sidebar() { const [collapsed, setCollapsed] = useState(false); const path = usePathname(); return <aside className={`sidebar ${collapsed ? "sidebar--collapsed" : ""}`}><div className="brand"><Sparkles className="brand__mark" size={16} strokeWidth={1.75} /><span className="brand__name">CEPHALON</span></div><nav aria-label="Primary navigation">{navigation.map((item) => <div className="nav-group" key={item.href}>{item.children && <span className="nav-group__label">{item.label}</span>}<NavLink item={item} path={path} />{item.children?.map((child) => <NavLink key={child.href} item={child} path={path} child />)}</div>)}</nav><IconButton label={collapsed ? "Expand navigation" : "Collapse navigation"} className="sidebar-toggle" onClick={() => setCollapsed(!collapsed)}>{collapsed ? <PanelLeftOpen size={16} strokeWidth={1.75} /> : <PanelLeftClose size={16} strokeWidth={1.75} />}</IconButton></aside>; }
function NavLink({ item, path, child = false }: { item: typeof flattenedNavigation[number]; path: string; child?: boolean }) { const Icon = item.icon; return <Link href={item.href} className={`nav-link ${path === item.href ? "nav-link--active" : ""} ${child ? "nav-link--child" : ""}`}><Icon className="nav-link__mark" size={16} strokeWidth={1.75} /><span className="nav-link__name">{item.label}</span></Link>; }
function CommandPalette({ open, onOpenChange }: { open: boolean; onOpenChange: (value: boolean) => void }) { const router = useRouter(); useEffect(() => { const listener = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); onOpenChange(!open); } }; window.addEventListener("keydown", listener); return () => window.removeEventListener("keydown", listener); }, [onOpenChange, open]); return <DialogPrimitive.Root open={open} onOpenChange={onOpenChange}><DialogPrimitive.Portal><DialogPrimitive.Overlay className="overlay palette-overlay" /><DialogPrimitive.Content className="palette"><DialogPrimitive.Title className="palette__title">Command palette</DialogPrimitive.Title><Command label="Command palette"><Command.Input autoFocus className="palette__input" placeholder="Navigate…" /><Command.List className="palette__list"><Command.Empty className="palette__empty">No navigation matches.</Command.Empty><Command.Group heading="Navigation" className="palette__group">{flattenedNavigation.map((item) => <Command.Item className="palette__item" key={item.href} value={item.label} onSelect={() => { router.push(item.href); onOpenChange(false); }}>{item.label}</Command.Item>)}</Command.Group><Command.Group heading="Search — coming soon" className="palette__group" aria-disabled="true"><Command.Item className="palette__item" disabled>Search items — coming soon</Command.Item></Command.Group></Command.List></Command></DialogPrimitive.Content></DialogPrimitive.Portal></DialogPrimitive.Root>; }
export function AppShell({ children }: { children: ReactNode }) { const [palette, setPalette] = useState(false); const path = usePathname(); return <div className="app-shell"><Sidebar /><div className="app-column"><header className="topbar"><span className="topbar__context">{titleFor(path)}</span><div className="topbar__actions"><button className="search-trigger" onClick={() => setPalette(true)}>Command palette <Kbd>Ctrl K</Kbd></button><span className="topbar__placeholder muted"><Globe size={16} strokeWidth={1.75} />World state</span><IconButton label="Notifications"><Bell size={16} strokeWidth={1.75} /></IconButton><IconButton label="Account"><CircleUser size={16} strokeWidth={1.75} /></IconButton></div></header><main className="main">{children}</main></div><CommandPalette open={palette} onOpenChange={setPalette} /></div>; }
