"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { type ReactNode, useEffect, useMemo, useState } from "react";
import { IconButton, Kbd } from "@/ui";
import { flattenedNavigation, navigation } from "./navigation";
import "./shell.css";

function titleFor(path: string) { return flattenedNavigation.find((item) => item.href === path)?.label ?? "Workspace"; }
function Sidebar() { const [collapsed, setCollapsed] = useState(false); const path = usePathname(); return <aside className={`sidebar ${collapsed ? "sidebar--collapsed" : ""}`}><div className="brand"><span className="brand__mark">◇</span><span className="brand__name">CEPHALON</span></div><nav aria-label="Primary navigation">{navigation.map((item) => <div className="nav-group" key={item.href}>{item.children && <span className="nav-group__label">{item.label}</span>}<NavLink item={item} path={path} />{item.children?.map((child) => <NavLink key={child.href} item={child} path={path} child />)}</div>)}</nav><IconButton label={collapsed ? "Expand navigation" : "Collapse navigation"} className="sidebar-toggle" onClick={() => setCollapsed(!collapsed)}>{collapsed ? "»" : "«"}</IconButton></aside>; }
function NavLink({ item, path, child = false }: { item: typeof flattenedNavigation[number]; path: string; child?: boolean }) { return <Link href={item.href} className={`nav-link ${path === item.href ? "nav-link--active" : ""} ${child ? "nav-link--child" : ""}`}><span className="nav-link__mark">{item.mark}</span><span className="nav-link__name">{item.label}</span></Link>; }
function CommandPalette({ open, onOpenChange }: { open: boolean; onOpenChange: (value: boolean) => void }) { const [query, setQuery] = useState(""); const router = useRouter(); const matches = useMemo(() => flattenedNavigation.filter((item) => item.label.toLowerCase().includes(query.toLowerCase())), [query]); useEffect(() => { const listener = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); onOpenChange(!open); } if (event.key === "Escape") onOpenChange(false); }; window.addEventListener("keydown", listener); return () => window.removeEventListener("keydown", listener); }, [onOpenChange, open]); if (!open) return null; return <div className="overlay" style={{ zIndex: "var(--z-palette)" }} onMouseDown={() => onOpenChange(false)}><section className="palette" role="dialog" aria-modal="true" aria-label="Command palette" onMouseDown={(event) => event.stopPropagation()}><input autoFocus className="palette__input" placeholder="Navigate…" aria-label="Command search" value={query} onChange={(event) => setQuery(event.target.value)} /><div className="palette__group"><div className="palette__label">Navigation</div>{matches.map((item) => <button className="palette__item" key={item.href} onClick={() => { router.push(item.href); onOpenChange(false); }}>{item.label}<span>{item.mark}</span></button>)}</div><div className="palette__group" aria-disabled="true"><div className="palette__label">Search</div><button className="palette__item" disabled>Search items — coming soon</button></div></section></div>; }
export function AppShell({ children }: { children: ReactNode }) { const [palette, setPalette] = useState(false); const path = usePathname(); return <div className="app-shell"><Sidebar /><div className="app-column"><header className="topbar"><span className="topbar__context">{titleFor(path)}</span><div className="topbar__actions"><button className="search-trigger" onClick={() => setPalette(true)}>Command palette <Kbd>Ctrl K</Kbd></button><span className="topbar__placeholder muted">World state</span><IconButton label="Notifications">◌</IconButton><IconButton label="Account">◉</IconButton></div></header><main className="main">{children}</main></div><CommandPalette open={palette} onOpenChange={setPalette} /></div>; }
