"use client";
import { type ButtonHTMLAttributes, type InputHTMLAttributes, type LabelHTMLAttributes, type ReactNode, useEffect, useId, useState } from "react";
import "./ui.css";

export const cx = (...v: Array<string | false | undefined>) => v.filter(Boolean).join(" ");
type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "danger"; size?: "sm" | "md"; leadingIcon?: ReactNode };
export function Button({ variant = "primary", size = "sm", leadingIcon, children, className, ...props }: ButtonProps) { return <button className={cx("button", `button--${variant}`, `button--${size}`, className)} {...props}>{leadingIcon}{children}</button>; }
export function IconButton({ label, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { label: string }) { return <button aria-label={label} className="icon-button" {...props}>{children}</button>; }
export function Panel({ title, actions, inset, chamfer, children, className }: { title?: ReactNode; actions?: ReactNode; inset?: boolean; chamfer?: boolean; children: ReactNode; className?: string }) { return <section className={cx("panel", inset && "panel--inset", chamfer && "chamfer", className)}>{title && <header className="panel__header"><span className="panel__title">{title}</span>{actions}</header>}<div className="panel__body">{children}</div></section>; }
export function Card({ children, className }: { children: ReactNode; className?: string }) { return <article className={cx("card", className)}>{children}</article>; }
export type ConfidenceTag = "verified" | "approximation" | "not-modeled" | "pending-verification";
const confidence: Record<ConfidenceTag, { label: string; description: string; tone: string }> = { verified: { label: "Verified", description: "Confirmed by tested mechanics.", tone: "positive" }, approximation: { label: "Approximation", description: "A useful estimate; exact behavior may vary.", tone: "warning" }, "not-modeled": { label: "Not modeled", description: "This mechanic is intentionally absent from this result.", tone: "muted" }, "pending-verification": { label: "Pending", description: "Awaiting verification against in-game behavior.", tone: "info" } };
export function Badge({ children, variant = "muted" }: { children: ReactNode; variant?: "muted" | "positive" | "warning" | "info" | "rare" | "legendary" }) { return <span className={`badge badge--${variant}`}>{children}</span>; }
export function ConfidenceBadge({ tag }: { tag: ConfidenceTag }) { const item = confidence[tag]; return <span className="tooltip"><Badge variant={item.tone as "positive"}>{item.label}</Badge><span role="tooltip" className="tooltip__content">{item.description}</span></span>; }
export function Stat({ label, value, delta, confidence: tag }: { label: string; value: ReactNode; delta?: number; confidence?: ConfidenceTag }) { return <div className="stat"><div className="stat__label">{label}</div><div className="stat__value">{value}</div>{(delta !== undefined || tag) && <div className="stat__meta">{delta !== undefined && <span className={delta >= 0 ? "delta--positive" : "delta--negative"}>{delta >= 0 ? "+" : ""}{delta}%</span>}{tag && <ConfidenceBadge tag={tag} />}</div>}</div>; }
export function StatGrid({ children }: { children: ReactNode }) { return <div className="stat-grid">{children}</div>; } export function StatRow({ children }: { children: ReactNode }) { return <div className="stat-row">{children}</div>; }
export function Table({ headers, rows, stickyHeader = false }: { headers: string[]; rows: ReactNode[][]; stickyHeader?: boolean }) { return <div className="table-wrap"><table className={cx("table", stickyHeader && "table--sticky")}><thead><tr>{headers.map((h) => <th key={h} scope="col">{h} ↕</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>; }
export function SegmentedControl({ options, value, onChange }: { options: string[]; value: string; onChange: (value: string) => void }) { const id = useId(); const key = (event: React.KeyboardEvent<HTMLDivElement>) => { const i = options.indexOf(value); if (event.key === "ArrowRight" || event.key === "ArrowLeft") { event.preventDefault(); onChange(options[(i + (event.key === "ArrowRight" ? 1 : options.length - 1)) % options.length]); } }; return <div role="group" aria-label="Segmented control" className="segmented" onKeyDown={key}>{options.map((option) => <button key={option} id={`${id}-${option}`} className="segment" aria-pressed={option === value} onClick={() => onChange(option)}>{option}</button>)}</div>; }
export function Tabs({ tabs }: { tabs: Array<{ label: string; content: ReactNode }> }) { const [active, setActive] = useState(0); return <div><div role="tablist" className="tabs">{tabs.map((tab, index) => <button key={tab.label} role="tab" aria-selected={active === index} className="tab" onClick={() => setActive(index)} onKeyDown={(e) => { if (e.key === "ArrowRight") setActive((index + 1) % tabs.length); if (e.key === "ArrowLeft") setActive((index + tabs.length - 1) % tabs.length); }}>{tab.label}</button>)}</div><div role="tabpanel">{tabs[active]?.content}</div></div>; }
export function Tooltip({ label, children }: { label: string; children: ReactNode }) { return <span className="tooltip">{children}<span role="tooltip" className="tooltip__content">{label}</span></span>; }
export function Dialog({ open, onOpenChange, title, children }: { open: boolean; onOpenChange: (value: boolean) => void; title: string; children: ReactNode }) { useEffect(() => { const listener = (e: KeyboardEvent) => { if (e.key === "Escape") onOpenChange(false); }; window.addEventListener("keydown", listener); return () => window.removeEventListener("keydown", listener); }, [onOpenChange]); if (!open) return null; return <div role="presentation" className="overlay" onMouseDown={() => onOpenChange(false)}><section role="dialog" aria-modal="true" aria-label={title} className="dialog" onMouseDown={(e) => e.stopPropagation()}><header className="panel__header"><span className="panel__title">{title}</span><IconButton label="Close" onClick={() => onOpenChange(false)}>×</IconButton></header><div className="panel__body">{children}</div></section></div>; }
export function Drawer(props: { open: boolean; onOpenChange: (value: boolean) => void; title: string; children: ReactNode }) { return <Dialog {...props} />; }
export function Label({ children, ...props }: LabelHTMLAttributes<HTMLLabelElement>) { return <label className="label" {...props}>{children}</label>; }
export function TextInput(props: InputHTMLAttributes<HTMLInputElement>) { return <input className="input" {...props} />; } export function NumberInput(props: InputHTMLAttributes<HTMLInputElement>) { return <input type="number" className="input number" {...props} />; } export function Kbd({ children }: { children: ReactNode }) { return <kbd className="kbd">{children}</kbd>; }
export function Sparkline({ values }: { values: number[] }) { const max = Math.max(...values), min = Math.min(...values), points = values.map((v, i) => `${(i / Math.max(values.length - 1, 1)) * 100},${100 - ((v - min) / Math.max(max - min, 1)) * 100}`).join(" "); return <svg className="viz-line" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Trend line"><polyline points={points} fill="none" stroke="var(--accent)" strokeWidth="3" vectorEffect="non-scaling-stroke" /></svg>; }
export function MiniBar({ value }: { value: number }) { return <div className="mini-bar" aria-label={`${value}%`}><div className="mini-bar__fill" style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>; } export function RadialMeter({ value }: { value: number }) { const r = 40, c = 2 * Math.PI * r; return <svg className="radial" viewBox="0 0 100 100" aria-label={`${value}%`}><circle className="radial__track" cx="50" cy="50" r={r} /><circle className="radial__value" cx="50" cy="50" r={r} strokeDasharray={c} strokeDashoffset={c * (1 - value / 100)} /></svg>; }
