/**
 * Wiki-locked Gravimag / Atmosphere paper for archguns with atmosphereStats (B21).
 * Source: Module:Weapons/data/archwing `*(Atmosphere)` default/charged attack
 * (Corvas + Velocitus lock Charged Shot; Morgha Auto-Burst; Arbucep 1st Attack).
 * Corvas Prime omitted — Atmosphere Charged == Space Charged (no overlay).
 * Generated from catalog after per-id wiki patches — do not blanket-edit.
 */
export const ARCH_ATMOSPHERE_GOLDENS: Array<{
  id: string;
  damage: number;
  impact?: number;
  puncture?: number;
  slash?: number;
  heat?: number;
  cold?: number;
  toxin?: number;
  electricity?: number;
  radiation?: number;
  viral?: number;
  corrosive?: number;
  blast?: number;
  gas?: number;
  magnetic?: number;
  criticalChance: number;
  criticalMultiplier: number;
  statusChance: number;
  fireRate: number;
  multishot: number;
  reloadTime?: number;
}> = [
  {
    id: "arbucep",
    damage: 32.0,
    blast: 32.0,
    criticalChance: 0.1,
    criticalMultiplier: 2.9,
    statusChance: 0.349,
    fireRate: 1.5,
    multishot: 1.0,
    reloadTime: 2.0,
  },
  {
    id: "cortege",
    damage: 180.0,
    heat: 180.0,
    criticalChance: 0.2,
    criticalMultiplier: 1.9,
    statusChance: 0.4,
    fireRate: 12.0,
    multishot: 1.0,
    reloadTime: 2.5,
  },
  {
    id: "corvas",
    damage: 160.0,
    impact: 128.0,
    puncture: 16.0,
    slash: 16.0,
    heat: 0.0,
    criticalChance: 0.4,
    criticalMultiplier: 3.0,
    statusChance: 0.013,
    fireRate: 2.0,
    multishot: 11.0,
    reloadTime: 2.0,
  },
  {
    id: "cyngas",
    damage: 240.0,
    impact: 80.0,
    puncture: 80.0,
    slash: 80.0,
    criticalChance: 0.2,
    criticalMultiplier: 2.2,
    statusChance: 0.3,
    fireRate: 6.67,
    multishot: 1.0,
    reloadTime: 1.2,
  },
  {
    id: "dual_decurion",
    damage: 190.0,
    impact: 85.5,
    puncture: 52.25,
    slash: 52.25,
    criticalChance: 0.28,
    criticalMultiplier: 2.2,
    statusChance: 0.14,
    fireRate: 10.42,
    multishot: 1.0,
    reloadTime: 1.4,
  },
  {
    id: "fluctus",
    damage: 500.0,
    impact: 100.0,
    puncture: 50.0,
    slash: 350.0,
    criticalChance: 0.22,
    criticalMultiplier: 2.0,
    statusChance: 0.16,
    fireRate: 5.0,
    multishot: 1.0,
    reloadTime: 3.0,
  },
  {
    id: "grattler",
    damage: 225.0,
    impact: 22.5,
    puncture: 180.0,
    slash: 22.5,
    criticalChance: 0.25,
    criticalMultiplier: 2.0,
    statusChance: 0.25,
    fireRate: 6.25,
    multishot: 1.0,
    reloadTime: 2.0,
  },
  {
    id: "imperator",
    damage: 100.0,
    impact: 40.0,
    puncture: 35.0,
    slash: 25.0,
    criticalChance: 0.24,
    criticalMultiplier: 2.0,
    statusChance: 0.12,
    fireRate: 16.7,
    multishot: 1.0,
    reloadTime: 2.0,
  },
  {
    id: "imperator_vandal",
    damage: 100.0,
    impact: 40.0,
    puncture: 35.0,
    slash: 25.0,
    criticalChance: 0.28,
    criticalMultiplier: 2.4,
    statusChance: 0.12,
    fireRate: 25.0,
    multishot: 1.0,
    reloadTime: 2.0,
  },
  {
    id: "kuva_ayanga",
    damage: 130.0,
    impact: 130.0,
    criticalChance: 0.35,
    criticalMultiplier: 2.0,
    statusChance: 0.2,
    fireRate: 4.58,
    multishot: 1.0,
    reloadTime: 3.0,
  },
  {
    id: "kuva_grattler",
    damage: 140.0,
    impact: 14.0,
    puncture: 112.0,
    slash: 14.0,
    criticalChance: 0.27,
    criticalMultiplier: 2.0,
    statusChance: 0.27,
    fireRate: 5.55,
    multishot: 1.0,
    reloadTime: 2.5,
  },
  {
    id: "larkspur",
    damage: 180.0,
    impact: 20.0,
    radiation: 160.0,
    criticalChance: 0.1,
    criticalMultiplier: 1.4,
    statusChance: 0.5,
    fireRate: 12.0,
    multishot: 1.0,
    reloadTime: 2.5,
  },
  {
    id: "larkspur_prime",
    damage: 180.0,
    impact: 20.0,
    radiation: 160.0,
    criticalChance: 0.14,
    criticalMultiplier: 1.6,
    statusChance: 0.5,
    fireRate: 12.0,
    multishot: 1.0,
    reloadTime: 2.5,
  },
  {
    id: "mandonel",
    damage: 180.0,
    impact: 50.0,
    puncture: 30.0,
    slash: 20.0,
    radiation: 80.0,
    criticalChance: 0.25,
    criticalMultiplier: 2.0,
    statusChance: 0.15,
    fireRate: 3.0,
    multishot: 8.0,
    reloadTime: 2.0,
  },
  {
    id: "mausolon",
    damage: 180.0,
    impact: 35.0,
    puncture: 70.0,
    heat: 75.0,
    criticalChance: 0.3,
    criticalMultiplier: 2.2,
    statusChance: 0.26,
    fireRate: 8.33,
    multishot: 1.0,
    reloadTime: 2.0,
  },
  {
    id: "morgha",
    damage: 64.0,
    impact: 64.0,
    criticalChance: 0.3,
    criticalMultiplier: 2.2,
    statusChance: 0.28,
    fireRate: 3.0,
    multishot: 1.0,
  },
  {
    id: "phaedra",
    damage: 116.0,
    impact: 29.0,
    puncture: 75.4,
    slash: 11.6,
    criticalChance: 0.14,
    criticalMultiplier: 2.0,
    statusChance: 0.3,
    fireRate: 18.75,
    multishot: 1.0,
    reloadTime: 2.0,
  },
  {
    id: "prisma_dual_decurions",
    damage: 220.0,
    impact: 99.0,
    puncture: 60.5,
    slash: 60.5,
    criticalChance: 0.3,
    criticalMultiplier: 2.2,
    statusChance: 0.24,
    fireRate: 12.5,
    multishot: 1.0,
    reloadTime: 1.4,
  },
  {
    id: "velocitus",
    damage: 3200.0,
    impact: 800.0,
    puncture: 800.0,
    slash: 800.0,
    magnetic: 800.0,
    criticalChance: 0.6,
    criticalMultiplier: 3.6,
    statusChance: 0.25,
    fireRate: 5.0,
    multishot: 1.0,
    reloadTime: 2.0,
  },
];
