/**
 * Non-Neutral stance combo hit-avg scalars (C6).
 * Source: Module:Stances/data — mean of per-hit Dmg% (incl. Slam), 1-decimal.
 * Neutral remains STANCE_AVG_DAMAGE_MULTIPLIER (B1 lock) — do not replace from this table.
 */

export type StanceComboDirectionKey = "forward" | "forwardBlock" | "block" | "heavy" | "slide";

export const STANCE_COMBO_DAMAGE_MULTIPLIER: Record<
  string,
  Partial<Record<StanceComboDirectionKey, number>>
> = {
  argent_scourge: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  atlantis_vulcan: { forward: 0.8, forwardBlock: 0.9, block: 0.9 },
  biting_piranha: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  blind_justice: { forward: 1.9, forwardBlock: 1.7, block: 2.0, slide: 1.0 },
  brutal_tide: { forward: 1.8, forwardBlock: 2.0, block: 1.8 },
  butchers_revelry: { forward: 1.0, forwardBlock: 1.8, block: 1.7 },
  celestial_nightfall: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  crashing_havoc: { forward: 1.0, forwardBlock: 1.5, block: 1.0 },
  crashing_timber: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  crushing_ruin: { forward: 1.6, forwardBlock: 2.0, block: 2.5 },
  cunning_aspect: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  cyclone_kraken: { forward: 1.0, forwardBlock: 2.2, block: 2.8 },
  dividing_blades: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  eleventh_storm: { forward: 1.7, forwardBlock: 1.8, block: 1.7 },
  fateful_truth: { forward: 1.0, forwardBlock: 1.0, block: 1.0, slide: 2.0 },
  final_harbinger: { forward: 1.5, forwardBlock: 1.4, block: 2.0 },
  four_riders: { forward: 1.4, forwardBlock: 1.9, block: 3.2, slide: 2.0 },
  fracturing_wind: { forward: 1.8, forwardBlock: 2.0, block: 2.5 },
  gaias_tragedy: { forward: 1.2, forwardBlock: 2.1, block: 1.9 },
  galeforce_dawn: { forward: 1.0, forwardBlock: 1.8, block: 3.0 },
  gemini_cross: { forward: 1.3, forwardBlock: 1.9, block: 1.5 },
  gleaming_talon: { forward: 1.2, forwardBlock: 1.9, block: 3.2 },
  lashing_coil: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  last_herald: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  mafic_rain: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  malicious_raptor: { forward: 1.5, forwardBlock: 1.6, block: 2.4 },
  mountains_edge: { forward: 1.1, forwardBlock: 2.2, block: 3.0 },
  noble_cadence: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  piercing_fury: { forward: 1.0, forwardBlock: 1.0, block: 1.3 },
  quaking_hand: { forward: 1.0, forwardBlock: 1.5, block: 1.0 },
  rending_crane: { forward: 2.0, forwardBlock: 2.0, block: 5.0 },
  rending_wind: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  rising_steel: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  scarlet_hurricane: { forward: 1.0, forwardBlock: 1.0, block: 1.0, slide: 3.0 },
  shadow_harvest: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  shattering_storm: { forward: 2.2, forwardBlock: 2.7, block: 3.0 },
  slicing_feathers: { forward: 1.4, forwardBlock: 1.4, block: 2.7 },
  sovereign_outcast: { forward: 1.0, forwardBlock: 1.2, block: 3.0 },
  stance_aurora_rush: { forward: 1.2, forwardBlock: 1.5, block: 2.3 },
  stance_bleeding_willow: { forward: 1.2, forwardBlock: 2.0, block: 1.2 },
  stance_bullet_dance: { forward: 1.7, forwardBlock: 1.9, block: 1.3 },
  stance_burning_wasp: { forward: 1.2, forwardBlock: 3.0, block: 3.0 },
  stance_carving_mantis: { forward: 1.4, forwardBlock: 2.0, block: 1.7 },
  stance_clashing_forest: { forward: 1.2, forwardBlock: 2.5, block: 1.7 },
  stance_cleaving_whirlwind: { forward: 1.4, forwardBlock: 2.1, block: 3.3 },
  stance_coiling_viper: { forward: 2.0, forwardBlock: 2.5, block: 2.0 },
  stance_crimson_dervish: { forward: 1.5, forwardBlock: 2.7, block: 2.8 },
  stance_crossing_snakes: { forward: 1.3, forwardBlock: 1.7, block: 1.3 },
  stance_decisive_judgement: { forward: 1.5, forwardBlock: 2.5, block: 4.0, slide: 2.0 },
  stance_defiled_snapdragon: { forward: 1.2, forwardBlock: 1.6, block: 5.0 },
  stance_flailing_branch: { forward: 2.5, forwardBlock: 2.2, block: 3.0 },
  stance_gnashing_payara: { forward: 1.2, forwardBlock: 2.8, block: 2.8 },
  stance_grim_fury_sparring: { forward: 1.7, forwardBlock: 3.0, block: 2.6 },
  stance_high_noon: { forward: 1.3, forwardBlock: 1.0, block: 3.2 },
  stance_homing_fang: { forward: 1.0, forwardBlock: 1.6, block: 2.4 },
  stance_iron_phoenix: { forward: 1.5, forwardBlock: 2.2, block: 2.3 },
  stance_pointed_wind: { forward: 1.8, forwardBlock: 1.8, block: 2.4 },
  stance_reaping_spiral: { forward: 2.0, forwardBlock: 2.2, block: 3.2 },
  stance_seismic_palm: { forward: 1.8, forwardBlock: 2.2, block: 2.2 },
  stance_shimmering_blight: { forward: 1.2, forwardBlock: 1.4, block: 1.2 },
  stance_sinking_talon: { forward: 1.0, forwardBlock: 1.6, block: 1.0 },
  stance_spinning_needle: { forward: 1.3, forwardBlock: 1.8, block: 2.3 },
  stance_stalking_fan: { forward: 2.0, forwardBlock: 2.0, block: 3.0 },
  stance_stinging_thorn: { forward: 1.6, forwardBlock: 2.0, block: 2.4 },
  stance_sundering_weave: { forward: 1.7, forwardBlock: 1.8, block: 5.0 },
  stance_swirling_tiger: { forward: 1.1, forwardBlock: 1.4, block: 1.2 },
  stance_swooping_falcon: { forward: 1.5, forwardBlock: 2.5, block: 3.0 },
  stance_temporal_royale: { forward: 1.3, forwardBlock: 2.8, block: 3.5 },
  stance_twirling_spire: { forward: 1.2, forwardBlock: 2.7, block: 1.5 },
  stance_vengeful_revenant: { forward: 1.5, forwardBlock: 1.8, block: 2.2 },
  stance_vermillion_storm: { forward: 1.3, forwardBlock: 0.8, block: 1.9 },
  stance_vulpine_mask: { forward: 1.1, forwardBlock: 2.0, block: 3.0 },
  stance_wise_razor: { forward: 2.7, forwardBlock: 2.5 },
  star_divide: { forward: 1.0, forwardBlock: 1.4, block: 1.0 },
  tainted_hydra: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  tranquil_cleave: { forward: 1.8, forwardBlock: 3.0, block: 4.0, slide: 2.0 },
  vicious_approach: { forward: 1.0, forwardBlock: 1.0, block: 1.0 },
  votive_onslaught: { forward: 1.0, forwardBlock: 1.9, block: 2.0 },
};

